version: '3'

services:
  nginx:
    ports:
      - '80:80'
  node-app1:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: 'admin'
      DB_PASSWORD: 'adminpw'
      DB_DATABASE: 'typeorm'
      PORT: 2222
      JWT_SECRET: 'thisisasamplesecret'
      JWT_ACCESS_EXPIRATION_MINUTES: 30
      JWT_REFRESH_EXPIRATION_DAYS: 30
      NODE_ENV: 'development'
    command: npm run dev
    depends_on:
      - mysql
  node-app2:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: 'admin'
      DB_PASSWORD: 'adminpw'
      DB_DATABASE: 'typeorm'
      PORT: 3333
      JWT_SECRET: 'thisisasamplesecret'
      JWT_ACCESS_EXPIRATION_MINUTES: 30
      JWT_REFRESH_EXPIRATION_DAYS: 30
      NODE_ENV: 'development'
    command: npm run dev
    depends_on:
      - mysql
  mysql:
    image: mysql:8
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpw'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'adminpw'
      MYSQL_DATABASE: 'typeorm'

  redis:
    image: redis
